### ISSUE TITLE
prebatch参数

### ISSUE THREAD

**Issue by cyjj** [fuhailin/DeePray#2]
想请问一下prebatch参数具体有什么益处。如果我的数据没有这一步处理是不是prebatch参数就设为1就行了。

**Comment by fuhailin** [comment]
prebatch用于匹配压缩的tfrecords数据，如果数据没有做特殊处理，默认就是1

Thanks
Hailin
________________________________
发件人: Matthew ***@***.***>
发送时间: Sunday, April 25, 2021 9:04:05 PM
收件人: fuhailin/DeePray ***@***.***>
抄送: Subscribed ***@***.***>
主题: [fuhailin/DeePray] prebatch参数 (#2)


想请问一下prebatch参数具体有什么益处。如果我的数据没有这一步处理是不是prebatch参数就设为1就行了。

―

**Comment by cyjj** [comment]
再冒昧问一下，我理解的prebatch就是一条tfrecord里面本来是LEN长度的数据，现在变成了prebatch*LEN的数据，这个为什么能起到压缩的作用呀。

**Comment by fuhailin** [comment]
用于将batch操作前移，这样的话一个example解析出来就是一个batch，相比于解析batch个examples样本，这样能较大提升io速度

**Comment by cyjj** [comment]
好的明白了，感谢
